### ISSUE TITLE
Error when closing OCR Reporter

### ISSUE THREAD

**Issue by Throdax** [dj-kata/sdvx_helper#25]
![image](https://github.com/user-attachments/assets/dcf4cf02-5842-42ed-befd-d7c752ac741a)

```
Traceback (most recent call last):
  File "ocr_reporter.py", line 449, in <module>
  File "ocr_reporter.py", line 54, in __init__
  File "ocr_reporter.py", line 345, in main
  File "ocr_reporter.py", line 183, in send_pkl
KeyError: 'url_webhook_reg'
```

**Comment by dj-kata** [comment]
Sorry, I forgot to modify the OCR reporter when I changed sdvx_helper to not include the webhook URL in the code. 
I will update the reporter binary.

**Comment by dj-kata** [comment]
I replaced ocr_reporter.zip in v.1.0.29 ([Link](https://github.com/dj-kata/sdvx_helper/releases/download/v.1.0.29/ocr_reporter.zip))
Thank you for your report.
